export enum Errors {
    CANDIDATE_DOES_NOT_EXIST = 'CANDIDATE_DOES_NOT_EXIST',
    USER_DOES_NOT_EXIST = 'USER_DOES_NOT_EXIST',
    JOB_DOES_NOT_EXIST = 'JOB_DOES_NOT_EXIST',
    USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
    CANDIDATE_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
    JOB_ALREADY_APPLIED = 'JOB_ALREADY_APPLIED'
}
export enum Alerts {
    SUCCESS = 'success',
    WARNING = 'warning',
    INFO = 'info',
    DANGER = 'danger'
}
